version: "3.7"
services:

## --------------------------- EVOLUTION API COM CORREÇÕES --------------------------- ##

  evolution_api:
    image: evolution-api-custom:latest ## Imagem custom com as correções
    container_name: evolution_api

    volumes:
      - evolution_instances:/evolution/instances

    networks:
      - AikaNet

    environment:
    ## ⚙️ Configurações Gerais
      - SERVER_URL=https://evolution.aikanakamura.com
      - AUTHENTICATION_API_KEY=988aeb4c9250361977ddacd0fdb1ba1e
      - AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES=true
      - DEL_INSTANCE=false
      - QRCODE_LIMIT=1902
      - LANGUAGE=pt-BR

    ## 📱 Configuração do Cliente
      - CONFIG_SESSION_PHONE_CLIENT=OrionDesign
      - CONFIG_SESSION_PHONE_NAME=Chrome

    ## 🗄️ Configuração do Banco de Dados
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=postgresql://postgres:47ff308dbc77c0ae050b729e9a60c59f@postgres:5432/evolution
      - DATABASE_CONNECTION_CLIENT_NAME=evolution
      - DATABASE_SAVE_DATA_INSTANCE=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true
      - DATABASE_SAVE_DATA_LABELS=true
      - DATABASE_SAVE_DATA_HISTORIC=true

    ## 🤖 Integrações
      - N8N_ENABLED=true
      - EVOAI_ENABLED=true
      - OPENAI_ENABLED=true
      - DIFY_ENABLED=true
      - TYPEBOT_ENABLED=true
      - TYPEBOT_API_VERSION=latest
      - CHATWOOT_ENABLED=true
      - CHATWOOT_MESSAGE_READ=true
      - CHATWOOT_MESSAGE_DELETE=true
      - CHATWOOT_IMPORT_DATABASE_CONNECTION_URI=postgresql://postgres:527f626a20e9e980bd49bb38813c1e12@pgvector:5432/chatwoot?sslmode=disable
      - CHATWOOT_IMPORT_PLACEHOLDER_MEDIA_MESSAGE=true

    ## 🧊 Cache Redis
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=redis://evolution_redis:6379/1
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=false
      - CACHE_LOCAL_ENABLED=false

    ## ☁️ S3
      - S3_ENABLED=false

    ## 💼 WhatsApp Business
      - WA_BUSINESS_TOKEN_WEBHOOK=evolution
      - WA_BUSINESS_URL=https://graph.facebook.com
      - WA_BUSINESS_VERSION=v23.0
      - WA_BUSINESS_LANGUAGE=pt_BR

    ## 📊 Outros
      - TELEMETRY=false
      - WEBSOCKET_ENABLED=false
      - SQS_ENABLED=false
      - RABBITMQ_ENABLED=false
      - WEBHOOK_GLOBAL_ENABLED=false

    labels:
      - traefik.enable=true
      - traefik.http.routers.evolution.rule=Host(`evolution.aikanakamura.com`)
      - traefik.http.routers.evolution.entrypoints=websecure
      - traefik.http.routers.evolution.tls.certresolver=letsencryptresolver
      - traefik.http.services.evolution.loadbalancer.server.port=8080

    restart: always

## --------------------------- REDIS --------------------------- ##

  evolution_redis:
    image: redis:latest
    container_name: evolution_redis
    command: [
        "redis-server",
        "--appendonly",
        "yes",
        "--port",
        "6379"
      ]

    volumes:
      - evolution_redis:/data

    networks:
      - AikaNet

    restart: always

## --------------------------- VOLUMES E REDES --------------------------- ##

volumes:
  evolution_instances:
    external: true
    name: evolution_instances
  evolution_redis:
    external: true
    name: evolution_redis

networks:
  AikaNet:
    external: true
    name: AikaNet
